[window]
opacity = 0.9

[font]
normal = { family = "0xProto Nerd Font Mono", style = "Regular" }
size = 9

[colors]
vi_mode_cursor = {text = '#000000', cursor = '#ffa0a0'}

[keyboard]
bindings = [
    # unicode for ♠: "\u2660"
    { key = "j", mods = "Control | Shift", chars = "♠" },
    { key = "k", mods = "Control | Shift", chars = "♡" }
]
